### ISSUE TITLE
CentOS7运行脚本报错, ubuntu19和debian9测试没有问题

### ISSUE THREAD

**Issue by PeterPanFormal** [liyanglan/ss-v2ray-plugin#1]
报错如下
./centos7-ss-install.sh:行219: 寻找匹配的 `"' 是遇到了未预期的文件结束符
./centos7-ss-install.sh:行234: 语法错误: 未预期的文件结尾

英文
./centos7-ss-install.sh: line 219: unexpected EOF while looking for matching `"'
./centos7-ss-install.sh: line 234: syntax error: unexpected end of file

**Comment by liyanglan** [comment]
已经修复。。。233

**Comment by PeterPanFormal** [comment]
已测试通过, Centos7没有问题. 
顺便一提, 我用vultr的机器测试了debian10 ubuntu18.04 ubuntu16.04 Ubuntu19.10 Ubuntu19.04 debian9 debian10 都没有问题. 
debian8不行, certbot无法用apt-get安装~ 
centos8报错 Failed to install libsodium~
感谢作者2333
